### ISSUE TITLE
Url parsing causing tests to fail

### ISSUE THREAD

**Issue by chasingSublimity** [activeprospect/leadconduit-types#103]
### Repro steps:

1) Install latest version of `leadconduit-types` (v4.15.1)

2) Run the following code
```
const types = require('leadconduit-types');

const website = types.url.parse;

console.log(website('testexample'));
```

3) Note that the `valid` attribute is set to `true`.
```
{ [String: 'http://testexample/']
  raw: 'testexample',
  protocol: 'http',
  host: 'testexample',
  port: null,
  path: '/',
  query: null,
  hash: null,
  valid: true 
}	
```
---

Is this the intended behavior? If so, we need to refactor the test referenced [here](https://github.com/activeprospect/leadconduit-integration-clearbit/issues/32).

FWIW, when `leadconduit-types` is installed at v4.14, the above code returns:
```
{ [String: 'testexample'] raw: 'testexample', valid: false }
```
which explains the broken test.

NB: It's very possible I'm misunderstanding something, so feel free to drop the knowledge hammer on this if I'm mistaken somewhere. 😊

**Comment by chasingSublimity** [comment]
https://github.com/activeprospect/leadconduit-types/blob/9357887f40b07685cf393da30a44a1f729cd7937/src/types/url.coffee#L4-L9

Right now, this function doesn't check to see if the host includes a TLD. Tweaking the host validation might be the easiest solution.

**Comment by chasingSublimity** [comment]
https://github.com/activeprospect/leadconduit-types/blob/master/spec/url-spec.coffee#L68-L75

Based on the code above, it appears that the parser is behaving correctly. Strings without TLD endings are supposed to pass through validation. In that case, what needs to be done to get the [this test](https://github.com/activeprospect/leadconduit-integration-clearbit/issues/32) passing?

**Comment by cgrayson** [comment]
Good sleuthing & great detail to reproduce & explain the issue. However, it's true: a hostname by itself can be a valid URI (e.g., if one has a server on the local network, that server's name can resolve.) That's how Node's URL parsing looks at it, and we've seen it in (rare) customer usage, too.
