### ISSUE TITLE
some state abbreviations are wrong

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-types#108]
Montana is MT, not MO, and Nebraska is NE, not MT. 😬

**Comment by mrjuicebox** [comment]
*Missing*
Mississippi	MS
Northwest Territories	NT
Nunavut	NU
Yukon	YT
Federated States of Micronesia	FM

*Needs correcting to*
Missouri	MO
Montana	MT
Saskatchewan	SK (misspelled)
Nebraska	NE (just remove the errant duplicate entry)
