### ISSUE TITLE
Passing '0' as a range type does not set min and max as '0'

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-types#19]
For example, passing monthly_sales: '0' returns

value { '0': '0', raw: '0', min: null, max: null, avg: null, valid: true }

**Comment by alexkwolfe** [comment]
This should no longer be an issue:

https://github.com/activeprospect/leadconduit-types/blob/5c1131c5f54a485d6ab9bbf366dbd24e6a5fe768/spec/range-spec.coffee#L133-L140
