### ISSUE TITLE
add 'street' type

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-types#22]
As currently used for the [address_1](https://github.com/activeprospect/leadconduit-fields/blob/dc370081d0f57e263b7082a1f142513bbe5498a4/fields/contact.json#L7) field.

**Comment by cgrayson** [comment]
Cf. the [LCC implementation](https://github.com/activeprospect/leadconduit/blob/0a48b73e7b0a21cecd73bd9396b3854e49c90006/trunk/projects/galt/src/com/leadconduit/domain/field/StreetAddressType.java), as [requested](https://activeprospect.slack.com/archives/leadconduit/p1464817534004861).

**Comment by alexkwolfe** [comment]
This is done.
