### ISSUE TITLE
Include extension in normalized phone format

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-types#24]
When normalizing phone number, the extension isn't included. It should be, otherwise it looks like we're dropping the extension. Also, including the extension makes it easier to pass through the normal phone (and extension when appropriate) to recipients without requiring custom mappings. 

See [Zendesk ticket #7071](https://activeprospect.zendesk.com/agent/tickets/7071) from 360 Partners.

**Comment by justinwinslow** [comment]
+1

**Comment by alexkwolfe** [comment]
This is fixed.
