### ISSUE TITLE
add "state" type

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-types#31]
To support abbreviated & fully spelled out names. Per [Slack discussion](https://activeprospect.slack.com/archives/leadconduit/p1435689009005349), a heavily-used Classic feature.

**Comment by cgrayson** [comment]
This was partially solved as of [this commit](https://github.com/activeprospect/leadconduit-types/commit/d38590c48457c44ec4bf9da7c0d0de76499a3bd2), but there is no `.abbr` component exposed.

**Comment by alexkwolfe** [comment]
The abbreviation is the normal form, so no component is necessary.

**Comment by alexkwolfe** [comment]
Can we close this?

**Comment by cgrayson** [comment]
Reckon so.
