### ISSUE TITLE
make 'includes' and 'does not include' work as substring tests

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-types#44]
it looks like `includes` and `does not include` could never behave differently than `is equal to` and `is not equal to`. As in [this test](https://github.com/activeprospect/leadconduit-rules/blob/master/spec/operators/includes-spec.coffee#L16-L17).

[Discussion](https://activeprospect.slack.com/archives/leadconduit/p1447277383000115).

**Comment by cgrayson** [comment]
I think that's a separate issue. Currently, at least, `includes` and `does not include` have specific meaning with regard to arrays. Though they seem similar, `includes` is explicitly written to _not_ do pattern matching in that context, so I'd be worried about "overloading" the operator like that.

For example, `['apple', 'beetle', 'carpenter'] includes 'bee'` would be `false` (but that array `includes 'beetle'` would be `true`). 

Maybe it would be fine. Maybe there should be a `contains` or `matches` instead. Maybe Alex W. has it all figured out & half written. :smiley:

**Comment by alexj** [comment]
That makes sense. `contains` would make more sense as a label too. Thanks Chris.

**Comment by alexkwolfe** [comment]
I also think what you've said makes sense, Chris. :+1:

**Comment by cgrayson** [comment]
After further discussion… 😊 rather than remove these, Wolfe & I decided it would be better to make them operate as substring tests (i.e., as Jones mentioned in the first place), after all. 

These still won't be full regex operators, though; that would still be a separate operator (say, `matches`). 

For the record we also talked about making this string operator have a distinct name other than the array operator (`includes`), such as `contains`. There's potential user confusion, when working with a rule, if they're offered operators that don't match what they're expecting based on data type. In the end we think it will be less confusing to have `includes` mean similar things with strings & arrays, instead of having different, synonymous names.

**Comment by cgrayson** [comment]
Looking at this now, I screwed up which issue should be open or closed. The valid string operators are _listed_ here, but the way they work is defined in `leadconduit-rules`. So, as I should have done on Sep 2, I'm: closing this, and reopening [rules #26](https://github.com/activeprospect/leadconduit-rules/issues/26).
