### ISSUE TITLE
Boolean type is not returning the ultimate evaluation

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-types#50]
For example: 

loan.has_financing: false 
{ valid: true, raw: 'false' }

loan.has_financing: 'blah'
{ valid: false, raw: 'blah' }

loan.has_financing: '1'
{ valid: true, raw: '1' }

To be clear, I would expect at least one more property in this object which shows me that the 1st instance evaluates to false, the second evaluates to 'invalid' or 'error', and that the third instance evaluates to true.

**Comment by alexkwolfe** [comment]
I'm not sure what the origin of that output is, but the boolean type parsing returns a Boolean object. Unless I'm misunderstanding something, adding the property as you suggest is unnecessary.

```coffeescript
parsed = require('leadconduit-types').boolean.parse('blah')

parsed.valueOf()
# => false

parsed.invalid
# => true

parsed.raw
# => '1'
```

**Comment by ros3bud** [comment]
The parsing is the key. Thanks for explaining.
