### ISSUE TITLE
adding a credential through the UI is not working correctly

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-types#53]
Looking more closely at what is going on - 

From the NREL flow, submitting a lead from postman and logging the values from my validate method -

When I log vars.nrel.api_key I see:

vars.nrel.api_key: { masked: false, valid: true }. 

I think this should be false when a key is not present.

**Comment by cgrayson** [comment]
It looks to me like the datamyx integration has `credential` type on user-entered values, and I believe that works. Maybe this is an issue in NREL's `validate()`?

**Comment by ros3bud** [comment]
That is working. I just verified. Our setups are different. Thanks.
