### ISSUE TITLE
state type fields are always "valid"

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-types#75]
As [mentioned in the tests](https://github.com/activeprospect/leadconduit-types/blob/master/spec/state-spec.coffee#L85), fields of type `state` always have `valid: true`:

>  \# There's no such thing as an invalid state right now because we really only provide
>  \# extra metadata for the 50 united states

**Comment by cgrayson** [comment]
Question about this in [Slack](https://activeprospect.slack.com/archives/C034BK84K/p1506721987000227) today, and I don't understand this reason myself. :-) Any insight, @alexkwolfe?

**Comment by alexkwolfe** [comment]
https://activeprospect.slack.com/archives/C034BK84K/p1506738068000018

**Comment by alexkwolfe** [comment]
Closed because we'll never know the entire universe of state names/codes.
